export const myProjects = [


  ////////html & css start//////////////
  {
    projectTitel: "FitLife",
    category: ["css"],
    imgPath: "img/5h.png",
    prg: "Website interface design fitlife-master using HTML and CSS and JavaScript.",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/Project-Files.git",
    more: "https://singap88a.github.io/Project-Files/",
  },
  {
    projectTitel: "eduweb-master",
    category: ["css"],
    imgPath: "img/6h.png",
    prg: "responsive website built from scratch using HTML, CSS ,JavaScript",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/eduweb-master.git",
    more: "https://singap88a.github.io/eduweb-master/",
  },
  {
    projectTitel: "dprod-master",
    category: ["css"],
    imgPath: "img/7h.png",
    prg: "responsive website built from scratch using HTML, CSS",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/dprod-master.git",
    more: "https://singap88a.github.io/dprod-master/",
  },
  {
    projectTitel: "Login interface",
    category: ["css"],
    imgPath: "img/1h.png",
    prg: "Create an excellent login interface using HTML and CSS",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/Login.git",
    more: "https://singap88a.github.io/Login/login.html",
  },
  {
    projectTitel: "Twitter",
    category: ["css"],
    imgPath: "img/2h.png",
    prg: "Website interface design Twitter using HTML and CSS. The website is responsive to all screens",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/Twitter.git",
    more: "https://singap88a.github.io/Twitter/s.html",
  },
  {
    projectTitel: "instagram",
    category: ["css"],
    imgPath: "img/3h.png",
    prg: "Website interface design instagram using HTML and CSS.",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/instagram1.git",
    more: "https://singap88a.github.io/instagram1/instagram/zz.html",
  },
  {
    projectTitel: "Food ",
    category: ["css"],
    imgPath: "img/4h.png",
    prg: "Designing a complete website interface for a restaurant using HTML and CSS",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/food.singap6.git",
    more: "https://ahmedsingap99.github.io/foodsingap4/food.html",
  },


  //////// js start///////
  {
    projectTitel: "A.S store",
    category: ["js"],
    imgPath: "img/1h-js.png",
    prg: "responsive website built from scratch using HTML, CSS, JavaScript, and Bootstrap.",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/A_S-store.git",
    more: "https://singap88a.github.io/A_S-store/index.html",
  },
  {
    projectTitel: "Foodie.",
    category: ["js"],
    imgPath: "img/2h-js.png",
    prg: "Designing a complete website interface for a restaurant using HTML and CSS and js",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/singap.food.git",
    more: "https://singap88a.github.io/singap.food/index.html",
  },
  {
    projectTitel: "LinkedIn",
    category: ["js"],
    imgPath: "img/3h-js.png",
    prg: "Designing a complete website interface for a restaurant using HTML and CSS and js",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/LinkedIn1.git",
    more: "https://singap88a.github.io/LinkedIn1/len.html",
  },
  {
    projectTitel: "fitlife-master",
    category: ["js"],
    imgPath: "img/4h-js.png",
    prg: "Website interface design fitlife-master using HTML and CSS and JavaScript.",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/GYM1.git",
    more: "https://singap88a.github.io/GYM1/fitlife-master/index.html",
  },
  {
    projectTitel: "Food",
    category: ["js"],
    imgPath: "img/5h-js.png",
    prg: "responsive website built from scratch using HTML, CSS, JavaScript, and Bootstrap.",
    github: "https://github.com/singap88a",
    link: "https://github.com/singap88a/omnifood.git",
    more: "https://singap88a.github.io/omnifood/food.html",
  },
  {
    projectTitel: "YouTube",
    category: ["js"],
    imgPath: "img/6h-js.png",
    prg: "responsive website built from scratch using HTML, CSS, JavaScript,",
    github: "https://github.com/singap88a",

    link: "https://github.com/singap88a/omnifood.git",
    more: "https://github.com/singap88a/youtube.git",
  },
  {
    projectTitel: "portfolio",
    category: ["js"],
    imgPath: "img/7h-js.png",
    prg: "Create a complete portfolio, multiple pages, responsive site",
    github: "https://github.com/singap88a",

    link: "https://github.com/singap88a/Portfolio.git",
    more: "https://singap88a.github.io/Portfolio/",
  },
  {
    projectTitel: "Dashboard",
    category: ["js"],
    imgPath: "img/8h-js.png",
    prg: "Create an effective dashboard using 'JavaScript' that includes a search function.",
    github: "https://github.com/singap88a",

    link: "https://github.com/singap88a/dashboard.git",
    more: "https://singap88a.github.io/dashboard/dashboard.html",
  },
  {
    projectTitel: "Arap_Ttalian",
    category: ["js","css"],
    imgPath: "img/9h-js.png",
    prg: "Business website for a shipping company for a client of the company owner",
    github: "https://github.com/singap88a",

    link: "https://github.com/singap88a/Arap_Ttalian.git",
    more: "https://singap88a.github.io/Arap_Ttalian/Arap.html",
  },
    //////// react start//////////////
     {
      projectTitel: "Shopping Cart ",
      category: ["react"],
      imgPath: "img/1r.png",
      prg: "Create a shopping cart with react js. The site is effective and responsive to all screens.",
      github: "https://github.com/singap88a",
      link: "https://github.com/singap88a/Shopping_Cart_ReactJS-main.git",
      more: "https://shopping-cart-3fa01.web.app",
    },
    {
      projectTitel: "portfolio ",
      category: ["react"],
      imgPath: "img/2r.png",
      prg: "Create a complete portfolio, multiple pages, responsive site 'react js'",
      github: "https://github.com/singap88a",
      link: "https://github.com/singap88a/portfolio-react.git",
      more: "https://portfolio-536da.web.app",
    },
    {
      projectTitel: "Ecommerce Greda ",
      category: ["react"],
      imgPath: "img/3r.png",
      prg: "Fully responsive ecommerce work with all screens'",
      github: "https://github.com/singap88a",
      link: "https://github.com/singap88a/greda-ecommerc.git",
      more: "",
    },
    {
      projectTitel: "JPress ",
      category: ["react"],
      imgPath: "img/4r.png",
      prg: "A platform connecting clients with service providers using AI-driven recommendations. ",
      github: "https://github.com/singap88a",
      link: "https://github.com/singap88a/JPress.git",
      more: "https://jpress-550f5.web.app",
    },
 
];
